logging:
  level:
    org:
      zalando:
        logbook: TRACE

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true


spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console.enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher