---F-I-L-M-S-------------------------------------------
create TABLE IF NOT EXISTS films (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(200),
  duration INTEGER,
  releaseDate DATE,
  mpa_rating_id INTEGER NOT NULL
);
---M-P-A---R-A-T-I-N-G---------------------------------
create TABLE IF NOT EXISTS mpa_rating (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(10) NOT NULL UNIQUE,
  description varchar(100) NOT NULL
);

alter table films add CONSTRAINT IF NOT EXISTS
 fk_films_rating FOREIGN KEY(mpa_rating_id) REFERENCES mpa_rating (id)
  ON delete RESTRICT;
---G-E-N-R-E-S-----------------------------------------
create TABLE IF NOT EXISTS genres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(32) NOT NULL UNIQUE
);
---F-I-L-M-S---G-E-N-R-E-S-----------------------------
create TABLE IF NOT EXISTS genres_film (
  film_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL
);
alter table genres_film add CONSTRAINT IF NOT EXISTS
 fk_genres_4_films FOREIGN KEY(genre_id) REFERENCES genres (id);--  ON DELETE RESTRICT;
alter table genres_film add CONSTRAINT IF NOT EXISTS
 fk_films_2_genres FOREIGN KEY(film_id) REFERENCES films (id);
alter table genres_film add CONSTRAINT IF NOT EXISTS
 unq_film_genre UNIQUE (film_id, genre_id);
---U-S-E-R-S-------------------------------------------
create TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR NOT NULL UNIQUE,
  name VARCHAR,
  email VARCHAR NOT NULL,
  birthday DATE
);
---F-R-I-E-N-D-S---------------------------------------
create TABLE IF NOT EXISTS friends (
  user_id_request INTEGER,
  user_id_friend INTEGER
);

alter table friends add CONSTRAINT IF NOT EXISTS
 fk_friends_user FOREIGN KEY(user_id_request) REFERENCES users (id);

alter table friends add CONSTRAINT IF NOT EXISTS
 fk_friends_friend FOREIGN KEY(user_id_friend) REFERENCES users (id);
---F-I-L-M-S---L-I-K-E-S-------------------------------
create TABLE IF NOT EXISTS films_like (
  film_id INTEGER,
  user_id INTEGER
);

alter table films_like add CONSTRAINT IF NOT EXISTS
 fk_like_user FOREIGN KEY(user_id) REFERENCES users (id)
--  ON delete CASCADE
  ;

alter table films_like add CONSTRAINT IF NOT EXISTS
 fk_like_film FOREIGN KEY(film_id) REFERENCES films (id)
--  ON delete CASCADE
  ;
---E-N-D---S-C-R-I-P-T---------------------------------
