---F-I-L-M-S-------------------------------------------
CREATE TABLE IF NOT EXISTS films (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  decription VARCHAR(200),
  duration INTEGER,
  release TIMESTAMP,
--  genre_id INTEGER NOT NULL,
  mpa_rating_id INTEGER NOT NULL
);
---M-P-A---R-A-T-I-N-G---------------------------------
CREATE TABLE IF NOT EXISTS mpa_rating (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating VARCHAR(10) NOT NULL UNIQUE,
  description varchar(100) NOT NULL
);

ALTER TABLE films ADD CONSTRAINT IF NOT EXISTS
 fk_films_rating FOREIGN KEY(mpa_rating_id) REFERENCES mpa_rating (id)
  ON DELETE RESTRICT;
---G-E-N-R-E-S-----------------------------------------
CREATE TABLE IF NOT EXISTS genres_film (
  genre_id INTEGER NOT NULL,
  film_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre VARCHAR NOT NULL UNIQUE
);

ALTER TABLE genres ADD CONSTRAINT IF NOT EXISTS
 fk_films_genre FOREIGN KEY(id) REFERENCES genres_film (genre_id);
--  ON DELETE RESTRICT;

ALTER TABLE films ADD CONSTRAINT IF NOT EXISTS
 fk_films_genre FOREIGN KEY(id) REFERENCES genres_film (film_id);
---U-S-E-R-S-------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR NOT NULL UNIQUE,
  name VARCHAR,
  email VARCHAR NOT NULL,
  birthdate TIMESTAMP
);
---F-R-I-E-N-D-S---------------------------------------
CREATE TABLE IF NOT EXISTS friends (
  user_id_request INTEGER,
  user_id_friend INTEGER
);

ALTER TABLE friends ADD CONSTRAINT IF NOT EXISTS
 fk_friends_user FOREIGN KEY(user_id_request) REFERENCES users (id);

ALTER TABLE friends ADD CONSTRAINT IF NOT EXISTS
 fk_friends_friend FOREIGN KEY(user_id_friend) REFERENCES users (id);
---F-I-L-M-S---L-I-K-E-S-------------------------------
CREATE TABLE IF NOT EXISTS films_likes (
  film_id INTEGER,
  user_id INTEGER
);

ALTER TABLE films_likes ADD CONSTRAINT IF NOT EXISTS
 fk_like_user FOREIGN KEY(user_id) REFERENCES users (id);

ALTER TABLE films_likes ADD CONSTRAINT IF NOT EXISTS
 fk_like_film FOREIGN KEY(film_id) REFERENCES films (id)
  ON DELETE CASCADE;
---F-I-L-M-S---G-E-N-R-E-S-----------------------------
CREATE TABLE IF NOT EXISTS film_genres (
  film_id INTEGER,
  genre_id INTEGER
);

ALTER TABLE film_genres ADD CONSTRAINT IF NOT EXISTS
 fk_film_genres FOREIGN KEY(film_id) REFERENCES films (id)
  ON DELETE CASCADE;

ALTER TABLE film_genres ADD CONSTRAINT IF NOT EXISTS
 fk_films_genre FOREIGN KEY(genre_id) REFERENCES genres (id)
  ON DELETE RESTRICT;

ALTER TABLE film_genres ADD CONSTRAINT IF NOT EXISTS
 unq_film_genre UNIQUE (film_id, genre_id);
---E-N-D---S-C-R-I-P-T---------------------------------